# -*- coding: utf-8 -*-
"""Udemy-Dashboard mercado financeiro

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qVDbA8ZTLbYM9-Ymatc7DGGLoplOXSE6
"""

!pip install turingquant
!pip install fundamentus

import pandas as pd
import turingquant as t
import fundamentus as f
import time
from google.colab import files

"""# Cotações diárias por empresa"""

tickers = t.support.get_ibov()
tickers = list(tickers['Ticker'])

cotacao = pd.DataFrame()

for ticker in tickers:
  try:
    novo_ticker = t.support.daily('GOY3EV6P00DZME99', ticker, br=True).assign(Ticker = ticker)
    cotacao = pd.concat([cotacao,novo_ticker])
  except:
    print(ticker)
    pass
  time.sleep(15)

cotacao[['Open', 'High', 'Low', 'Close', 'Ticker']].to_excel('Cotações diárias por empresa.xlsx', sheet_name = 'Cotações diárias por empresa')
files.download('Cotações diárias por empresa.xlsx')

"""# Informações e indicadores por empresa"""

empresas = f.get_papel(tickers)

empresas[['Empresa', 'Setor', 'Subsetor', 'Cotacao', 'PL', 'Div_Yield', 'Cres_Rec_5a', 'Marg_Liquida', 'ROIC', 'ROE','Liquidez_Corr']].to_excel('Informações e indicadores por empresa.xlsx', sheet_name = 'Informações e indicadores por empresa')
files.download('Informações e indicadores por empresa.xlsx')

"""# Indicadores fundamentalistas"""

indicadores = f.get_resultado()

indicadores.to_excel('Indicadores fundamentalistas.xlsx', sheet_name = 'Indicadores fundamentalistas')
files.download('Indicadores fundamentalistas.xlsx')